name: fitmaps
description: A lecture hall navigation app for schools

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  http: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/floors/
    - data/parsed_data/
    - data/raw_htmls/

flutter_launcher_icons:
  android: true
  web:
    generate: true
    image_path: "assets/images/ic_launcher.png"
    background_color: "#ffffff"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/images/ic_launcher.png"
    icon_size: 48
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"

